server:
  port: ${PORT:8085}

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:medifind_notification_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:noreply@medifind.com}
    password: "${MAIL_PASSWORD:}"
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:false}

app:
  mail:
    enabled: ${MAIL_ENABLED:false}
  sms:
    enabled: ${SMS_ENABLED:false}
    provider: ${SMS_PROVIDER:mock}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
