package com.medifind.doctor.entity;

public enum Specialization {
    GENERAL_PHYSICIAN,
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIC,
    PEDIATRICIAN,
    GYNECOLOGIST,
    PSYCHIATRIST,
    OPHTHALMOLOGIST,
    ENT_SPECIALIST,
    DENTIST,
    GASTROENTEROLOGIST,
    PULMONOLOGIST,
    UROLOGIST,
    ONCOLOGIST,
    ENDOCRINOLOGIST,
    NEPHROLOGIST,
    OTHER
}
