// Generated by delombok at Tue Aug 11 10:11:55 IST 2026
package com.medifind.appointment.dto;

import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.time.LocalTime;

public class AppointmentRequest {
    @NotNull(message = "Doctor ID is required")
    private Long doctorId;
    @NotNull(message = "Appointment date is required")
    @FutureOrPresent(message = "Appointment date cannot be in the past")
    private LocalDate appointmentDate;
    @NotNull(message = "Appointment time is required")
    private LocalTime appointmentTime;
    @NotBlank(message = "Reason is required")
    private String reason;

    @java.lang.SuppressWarnings("all")
    public AppointmentRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getDoctorId() {
        return this.doctorId;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getAppointmentDate() {
        return this.appointmentDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalTime getAppointmentTime() {
        return this.appointmentTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getReason() {
        return this.reason;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoctorId(final Long doctorId) {
        this.doctorId = doctorId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAppointmentDate(final LocalDate appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setAppointmentTime(final LocalTime appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setReason(final String reason) {
        this.reason = reason;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AppointmentRequest)) return false;
        final AppointmentRequest other = (AppointmentRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$doctorId = this.getDoctorId();
        final java.lang.Object other$doctorId = other.getDoctorId();
        if (this$doctorId == null ? other$doctorId != null : !this$doctorId.equals(other$doctorId)) return false;
        final java.lang.Object this$appointmentDate = this.getAppointmentDate();
        final java.lang.Object other$appointmentDate = other.getAppointmentDate();
        if (this$appointmentDate == null ? other$appointmentDate != null : !this$appointmentDate.equals(other$appointmentDate)) return false;
        final java.lang.Object this$appointmentTime = this.getAppointmentTime();
        final java.lang.Object other$appointmentTime = other.getAppointmentTime();
        if (this$appointmentTime == null ? other$appointmentTime != null : !this$appointmentTime.equals(other$appointmentTime)) return false;
        final java.lang.Object this$reason = this.getReason();
        final java.lang.Object other$reason = other.getReason();
        if (this$reason == null ? other$reason != null : !this$reason.equals(other$reason)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AppointmentRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $doctorId = this.getDoctorId();
        result = result * PRIME + ($doctorId == null ? 43 : $doctorId.hashCode());
        final java.lang.Object $appointmentDate = this.getAppointmentDate();
        result = result * PRIME + ($appointmentDate == null ? 43 : $appointmentDate.hashCode());
        final java.lang.Object $appointmentTime = this.getAppointmentTime();
        result = result * PRIME + ($appointmentTime == null ? 43 : $appointmentTime.hashCode());
        final java.lang.Object $reason = this.getReason();
        result = result * PRIME + ($reason == null ? 43 : $reason.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AppointmentRequest(doctorId=" + this.getDoctorId() + ", appointmentDate=" + this.getAppointmentDate() + ", appointmentTime=" + this.getAppointmentTime() + ", reason=" + this.getReason() + ")";
    }
}
