// Generated by delombok at Tue Aug 11 10:11:55 IST 2026
package com.medifind.appointment.dto;

import com.medifind.appointment.entity.AppointmentStatus;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;

public class AppointmentResponse {
    private Long id;
    private Long userId;
    private UserResponse user;
    private Long doctorId;
    private DoctorResponse doctor;
    private LocalDate appointmentDate;
    private LocalTime appointmentTime;
    private String reason;
    private AppointmentStatus status;
    private String notes;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @java.lang.SuppressWarnings("all")
    AppointmentResponse(final Long id, final Long userId, final UserResponse user, final Long doctorId, final DoctorResponse doctor, final LocalDate appointmentDate, final LocalTime appointmentTime, final String reason, final AppointmentStatus status, final String notes, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.userId = userId;
        this.user = user;
        this.doctorId = doctorId;
        this.doctor = doctor;
        this.appointmentDate = appointmentDate;
        this.appointmentTime = appointmentTime;
        this.reason = reason;
        this.status = status;
        this.notes = notes;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }


    @java.lang.SuppressWarnings("all")
    public static class AppointmentResponseBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private Long userId;
        @java.lang.SuppressWarnings("all")
        private UserResponse user;
        @java.lang.SuppressWarnings("all")
        private Long doctorId;
        @java.lang.SuppressWarnings("all")
        private DoctorResponse doctor;
        @java.lang.SuppressWarnings("all")
        private LocalDate appointmentDate;
        @java.lang.SuppressWarnings("all")
        private LocalTime appointmentTime;
        @java.lang.SuppressWarnings("all")
        private String reason;
        @java.lang.SuppressWarnings("all")
        private AppointmentStatus status;
        @java.lang.SuppressWarnings("all")
        private String notes;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        AppointmentResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder user(final UserResponse user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder doctorId(final Long doctorId) {
            this.doctorId = doctorId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder doctor(final DoctorResponse doctor) {
            this.doctor = doctor;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder appointmentDate(final LocalDate appointmentDate) {
            this.appointmentDate = appointmentDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder appointmentTime(final LocalTime appointmentTime) {
            this.appointmentTime = appointmentTime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder reason(final String reason) {
            this.reason = reason;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder status(final AppointmentStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public AppointmentResponse.AppointmentResponseBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public AppointmentResponse build() {
            return new AppointmentResponse(this.id, this.userId, this.user, this.doctorId, this.doctor, this.appointmentDate, this.appointmentTime, this.reason, this.status, this.notes, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "AppointmentResponse.AppointmentResponseBuilder(id=" + this.id + ", userId=" + this.userId + ", user=" + this.user + ", doctorId=" + this.doctorId + ", doctor=" + this.doctor + ", appointmentDate=" + this.appointmentDate + ", appointmentTime=" + this.appointmentTime + ", reason=" + this.reason + ", status=" + this.status + ", notes=" + this.notes + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static AppointmentResponse.AppointmentResponseBuilder builder() {
        return new AppointmentResponse.AppointmentResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public UserResponse getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public Long getDoctorId() {
        return this.doctorId;
    }

    @java.lang.SuppressWarnings("all")
    public DoctorResponse getDoctor() {
        return this.doctor;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getAppointmentDate() {
        return this.appointmentDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalTime getAppointmentTime() {
        return this.appointmentTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getReason() {
        return this.reason;
    }

    @java.lang.SuppressWarnings("all")
    public AppointmentStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final UserResponse user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoctorId(final Long doctorId) {
        this.doctorId = doctorId;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoctor(final DoctorResponse doctor) {
        this.doctor = doctor;
    }

    @java.lang.SuppressWarnings("all")
    public void setAppointmentDate(final LocalDate appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setAppointmentTime(final LocalTime appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setReason(final String reason) {
        this.reason = reason;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final AppointmentStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AppointmentResponse)) return false;
        final AppointmentResponse other = (AppointmentResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$doctorId = this.getDoctorId();
        final java.lang.Object other$doctorId = other.getDoctorId();
        if (this$doctorId == null ? other$doctorId != null : !this$doctorId.equals(other$doctorId)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$doctor = this.getDoctor();
        final java.lang.Object other$doctor = other.getDoctor();
        if (this$doctor == null ? other$doctor != null : !this$doctor.equals(other$doctor)) return false;
        final java.lang.Object this$appointmentDate = this.getAppointmentDate();
        final java.lang.Object other$appointmentDate = other.getAppointmentDate();
        if (this$appointmentDate == null ? other$appointmentDate != null : !this$appointmentDate.equals(other$appointmentDate)) return false;
        final java.lang.Object this$appointmentTime = this.getAppointmentTime();
        final java.lang.Object other$appointmentTime = other.getAppointmentTime();
        if (this$appointmentTime == null ? other$appointmentTime != null : !this$appointmentTime.equals(other$appointmentTime)) return false;
        final java.lang.Object this$reason = this.getReason();
        final java.lang.Object other$reason = other.getReason();
        if (this$reason == null ? other$reason != null : !this$reason.equals(other$reason)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AppointmentResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $doctorId = this.getDoctorId();
        result = result * PRIME + ($doctorId == null ? 43 : $doctorId.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $doctor = this.getDoctor();
        result = result * PRIME + ($doctor == null ? 43 : $doctor.hashCode());
        final java.lang.Object $appointmentDate = this.getAppointmentDate();
        result = result * PRIME + ($appointmentDate == null ? 43 : $appointmentDate.hashCode());
        final java.lang.Object $appointmentTime = this.getAppointmentTime();
        result = result * PRIME + ($appointmentTime == null ? 43 : $appointmentTime.hashCode());
        final java.lang.Object $reason = this.getReason();
        result = result * PRIME + ($reason == null ? 43 : $reason.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AppointmentResponse(id=" + this.getId() + ", userId=" + this.getUserId() + ", user=" + this.getUser() + ", doctorId=" + this.getDoctorId() + ", doctor=" + this.getDoctor() + ", appointmentDate=" + this.getAppointmentDate() + ", appointmentTime=" + this.getAppointmentTime() + ", reason=" + this.getReason() + ", status=" + this.getStatus() + ", notes=" + this.getNotes() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }
}
