// Generated by delombok at Tue Aug 11 10:11:55 IST 2026
package com.medifind.appointment.dto;

public class DoctorAvailabilityResponse {
    private Long doctorId;
    private boolean available;
    private String workingDays;
    private String consultationStartTime;
    private String consultationEndTime;
    private Integer appointmentDuration;

    @java.lang.SuppressWarnings("all")
    public DoctorAvailabilityResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getDoctorId() {
        return this.doctorId;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAvailable() {
        return this.available;
    }

    @java.lang.SuppressWarnings("all")
    public String getWorkingDays() {
        return this.workingDays;
    }

    @java.lang.SuppressWarnings("all")
    public String getConsultationStartTime() {
        return this.consultationStartTime;
    }

    @java.lang.SuppressWarnings("all")
    public String getConsultationEndTime() {
        return this.consultationEndTime;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getAppointmentDuration() {
        return this.appointmentDuration;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoctorId(final Long doctorId) {
        this.doctorId = doctorId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvailable(final boolean available) {
        this.available = available;
    }

    @java.lang.SuppressWarnings("all")
    public void setWorkingDays(final String workingDays) {
        this.workingDays = workingDays;
    }

    @java.lang.SuppressWarnings("all")
    public void setConsultationStartTime(final String consultationStartTime) {
        this.consultationStartTime = consultationStartTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setConsultationEndTime(final String consultationEndTime) {
        this.consultationEndTime = consultationEndTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setAppointmentDuration(final Integer appointmentDuration) {
        this.appointmentDuration = appointmentDuration;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DoctorAvailabilityResponse)) return false;
        final DoctorAvailabilityResponse other = (DoctorAvailabilityResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isAvailable() != other.isAvailable()) return false;
        final java.lang.Object this$doctorId = this.getDoctorId();
        final java.lang.Object other$doctorId = other.getDoctorId();
        if (this$doctorId == null ? other$doctorId != null : !this$doctorId.equals(other$doctorId)) return false;
        final java.lang.Object this$appointmentDuration = this.getAppointmentDuration();
        final java.lang.Object other$appointmentDuration = other.getAppointmentDuration();
        if (this$appointmentDuration == null ? other$appointmentDuration != null : !this$appointmentDuration.equals(other$appointmentDuration)) return false;
        final java.lang.Object this$workingDays = this.getWorkingDays();
        final java.lang.Object other$workingDays = other.getWorkingDays();
        if (this$workingDays == null ? other$workingDays != null : !this$workingDays.equals(other$workingDays)) return false;
        final java.lang.Object this$consultationStartTime = this.getConsultationStartTime();
        final java.lang.Object other$consultationStartTime = other.getConsultationStartTime();
        if (this$consultationStartTime == null ? other$consultationStartTime != null : !this$consultationStartTime.equals(other$consultationStartTime)) return false;
        final java.lang.Object this$consultationEndTime = this.getConsultationEndTime();
        final java.lang.Object other$consultationEndTime = other.getConsultationEndTime();
        if (this$consultationEndTime == null ? other$consultationEndTime != null : !this$consultationEndTime.equals(other$consultationEndTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DoctorAvailabilityResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isAvailable() ? 79 : 97);
        final java.lang.Object $doctorId = this.getDoctorId();
        result = result * PRIME + ($doctorId == null ? 43 : $doctorId.hashCode());
        final java.lang.Object $appointmentDuration = this.getAppointmentDuration();
        result = result * PRIME + ($appointmentDuration == null ? 43 : $appointmentDuration.hashCode());
        final java.lang.Object $workingDays = this.getWorkingDays();
        result = result * PRIME + ($workingDays == null ? 43 : $workingDays.hashCode());
        final java.lang.Object $consultationStartTime = this.getConsultationStartTime();
        result = result * PRIME + ($consultationStartTime == null ? 43 : $consultationStartTime.hashCode());
        final java.lang.Object $consultationEndTime = this.getConsultationEndTime();
        result = result * PRIME + ($consultationEndTime == null ? 43 : $consultationEndTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "DoctorAvailabilityResponse(doctorId=" + this.getDoctorId() + ", available=" + this.isAvailable() + ", workingDays=" + this.getWorkingDays() + ", consultationStartTime=" + this.getConsultationStartTime() + ", consultationEndTime=" + this.getConsultationEndTime() + ", appointmentDuration=" + this.getAppointmentDuration() + ")";
    }
}
