// Generated by delombok at Tue Aug 11 10:11:55 IST 2026
package com.medifind.appointment.dto;

public class DoctorResponse {
    private Long id;
    private String doctorName;
    private String specialization;
    private String qualification;
    private Integer experience;
    private Double consultationFee;
    private Double rating;
    private Long hospitalId;
    private String city;
    private String state;
    private String phoneNumber;
    private String email;
    private String profileImage;
    private boolean available;

    @java.lang.SuppressWarnings("all")
    public DoctorResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getDoctorName() {
        return this.doctorName;
    }

    @java.lang.SuppressWarnings("all")
    public String getSpecialization() {
        return this.specialization;
    }

    @java.lang.SuppressWarnings("all")
    public String getQualification() {
        return this.qualification;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getExperience() {
        return this.experience;
    }

    @java.lang.SuppressWarnings("all")
    public Double getConsultationFee() {
        return this.consultationFee;
    }

    @java.lang.SuppressWarnings("all")
    public Double getRating() {
        return this.rating;
    }

    @java.lang.SuppressWarnings("all")
    public Long getHospitalId() {
        return this.hospitalId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getProfileImage() {
        return this.profileImage;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isAvailable() {
        return this.available;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setDoctorName(final String doctorName) {
        this.doctorName = doctorName;
    }

    @java.lang.SuppressWarnings("all")
    public void setSpecialization(final String specialization) {
        this.specialization = specialization;
    }

    @java.lang.SuppressWarnings("all")
    public void setQualification(final String qualification) {
        this.qualification = qualification;
    }

    @java.lang.SuppressWarnings("all")
    public void setExperience(final Integer experience) {
        this.experience = experience;
    }

    @java.lang.SuppressWarnings("all")
    public void setConsultationFee(final Double consultationFee) {
        this.consultationFee = consultationFee;
    }

    @java.lang.SuppressWarnings("all")
    public void setRating(final Double rating) {
        this.rating = rating;
    }

    @java.lang.SuppressWarnings("all")
    public void setHospitalId(final Long hospitalId) {
        this.hospitalId = hospitalId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setProfileImage(final String profileImage) {
        this.profileImage = profileImage;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvailable(final boolean available) {
        this.available = available;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DoctorResponse)) return false;
        final DoctorResponse other = (DoctorResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isAvailable() != other.isAvailable()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$experience = this.getExperience();
        final java.lang.Object other$experience = other.getExperience();
        if (this$experience == null ? other$experience != null : !this$experience.equals(other$experience)) return false;
        final java.lang.Object this$consultationFee = this.getConsultationFee();
        final java.lang.Object other$consultationFee = other.getConsultationFee();
        if (this$consultationFee == null ? other$consultationFee != null : !this$consultationFee.equals(other$consultationFee)) return false;
        final java.lang.Object this$rating = this.getRating();
        final java.lang.Object other$rating = other.getRating();
        if (this$rating == null ? other$rating != null : !this$rating.equals(other$rating)) return false;
        final java.lang.Object this$hospitalId = this.getHospitalId();
        final java.lang.Object other$hospitalId = other.getHospitalId();
        if (this$hospitalId == null ? other$hospitalId != null : !this$hospitalId.equals(other$hospitalId)) return false;
        final java.lang.Object this$doctorName = this.getDoctorName();
        final java.lang.Object other$doctorName = other.getDoctorName();
        if (this$doctorName == null ? other$doctorName != null : !this$doctorName.equals(other$doctorName)) return false;
        final java.lang.Object this$specialization = this.getSpecialization();
        final java.lang.Object other$specialization = other.getSpecialization();
        if (this$specialization == null ? other$specialization != null : !this$specialization.equals(other$specialization)) return false;
        final java.lang.Object this$qualification = this.getQualification();
        final java.lang.Object other$qualification = other.getQualification();
        if (this$qualification == null ? other$qualification != null : !this$qualification.equals(other$qualification)) return false;
        final java.lang.Object this$city = this.getCity();
        final java.lang.Object other$city = other.getCity();
        if (this$city == null ? other$city != null : !this$city.equals(other$city)) return false;
        final java.lang.Object this$state = this.getState();
        final java.lang.Object other$state = other.getState();
        if (this$state == null ? other$state != null : !this$state.equals(other$state)) return false;
        final java.lang.Object this$phoneNumber = this.getPhoneNumber();
        final java.lang.Object other$phoneNumber = other.getPhoneNumber();
        if (this$phoneNumber == null ? other$phoneNumber != null : !this$phoneNumber.equals(other$phoneNumber)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$profileImage = this.getProfileImage();
        final java.lang.Object other$profileImage = other.getProfileImage();
        if (this$profileImage == null ? other$profileImage != null : !this$profileImage.equals(other$profileImage)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DoctorResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isAvailable() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $experience = this.getExperience();
        result = result * PRIME + ($experience == null ? 43 : $experience.hashCode());
        final java.lang.Object $consultationFee = this.getConsultationFee();
        result = result * PRIME + ($consultationFee == null ? 43 : $consultationFee.hashCode());
        final java.lang.Object $rating = this.getRating();
        result = result * PRIME + ($rating == null ? 43 : $rating.hashCode());
        final java.lang.Object $hospitalId = this.getHospitalId();
        result = result * PRIME + ($hospitalId == null ? 43 : $hospitalId.hashCode());
        final java.lang.Object $doctorName = this.getDoctorName();
        result = result * PRIME + ($doctorName == null ? 43 : $doctorName.hashCode());
        final java.lang.Object $specialization = this.getSpecialization();
        result = result * PRIME + ($specialization == null ? 43 : $specialization.hashCode());
        final java.lang.Object $qualification = this.getQualification();
        result = result * PRIME + ($qualification == null ? 43 : $qualification.hashCode());
        final java.lang.Object $city = this.getCity();
        result = result * PRIME + ($city == null ? 43 : $city.hashCode());
        final java.lang.Object $state = this.getState();
        result = result * PRIME + ($state == null ? 43 : $state.hashCode());
        final java.lang.Object $phoneNumber = this.getPhoneNumber();
        result = result * PRIME + ($phoneNumber == null ? 43 : $phoneNumber.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $profileImage = this.getProfileImage();
        result = result * PRIME + ($profileImage == null ? 43 : $profileImage.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "DoctorResponse(id=" + this.getId() + ", doctorName=" + this.getDoctorName() + ", specialization=" + this.getSpecialization() + ", qualification=" + this.getQualification() + ", experience=" + this.getExperience() + ", consultationFee=" + this.getConsultationFee() + ", rating=" + this.getRating() + ", hospitalId=" + this.getHospitalId() + ", city=" + this.getCity() + ", state=" + this.getState() + ", phoneNumber=" + this.getPhoneNumber() + ", email=" + this.getEmail() + ", profileImage=" + this.getProfileImage() + ", available=" + this.isAvailable() + ")";
    }
}
