// Generated by delombok at Tue Aug 11 10:11:55 IST 2026
package com.medifind.appointment.config;

import com.medifind.appointment.security.JwtAuthFilter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

/**
 * Spring Security configuration for the Hospital Service.
 * All hospital write endpoints require ADMIN; reads require authentication.
 * Method-level security (@PreAuthorize) is enabled for fine-grained control.
 */
@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public class SecurityConfig {
    private final JwtAuthFilter jwtAuthFilter;

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        
        // Swagger / OpenAPI — publicly accessible
        // Write operations — ADMIN only
        // Read operations — any authenticated user
        http.csrf(AbstractHttpConfigurer::disable).authorizeHttpRequests(auth -> auth.requestMatchers("/v3/api-docs/**", "/swagger-ui/**", "/swagger-ui.html").permitAll().requestMatchers(HttpMethod.POST, "/api/hospitals/**").hasAuthority("ROLE_ADMIN").requestMatchers(HttpMethod.PUT, "/api/hospitals/**").hasAuthority("ROLE_ADMIN").requestMatchers(HttpMethod.DELETE, "/api/hospitals/**").hasAuthority("ROLE_ADMIN").requestMatchers(HttpMethod.GET, "/api/hospitals/**").authenticated().anyRequest().authenticated()).sessionManagement(sess -> sess.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).addFilterBefore(jwtAuthFilter, UsernamePasswordAuthenticationFilter.class);
        return http.build();
    }

    @java.lang.SuppressWarnings("all")
    public SecurityConfig(final JwtAuthFilter jwtAuthFilter) {
        this.jwtAuthFilter = jwtAuthFilter;
    }
}
