// Generated by delombok at Tue Aug 11 10:11:55 IST 2026
package com.medifind.appointment.security;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.lang.NonNull;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
import java.io.IOException;
import java.util.List;
import java.util.stream.Collectors;

/**
 * One-shot per-request filter that validates the Bearer JWT and
 * populates the {@link SecurityContextHolder} with the authenticated principal
 * and their roles — enabling {@code @PreAuthorize} checks downstream.
 */
@Component
public class JwtAuthFilter extends OncePerRequestFilter {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(JwtAuthFilter.class);
    private final JwtService jwtService;

    @Override
    protected void doFilterInternal(@NonNull HttpServletRequest request, @NonNull HttpServletResponse response, @NonNull FilterChain filterChain) throws ServletException, IOException {
        final String authHeader = request.getHeader("Authorization");
        if (authHeader == null || !authHeader.startsWith("Bearer ")) {
            filterChain.doFilter(request, response);
            return;
        }
        try {
            final String jwt = authHeader.substring(7);
            final String username = jwtService.extractUsername(jwt);
            if (username != null && SecurityContextHolder.getContext().getAuthentication() == null) {
                if (jwtService.isTokenValid(jwt)) {
                    List<SimpleGrantedAuthority> authorities = jwtService.extractRoles(jwt).stream().map(SimpleGrantedAuthority::new).collect(Collectors.toList());
                    UsernamePasswordAuthenticationToken authToken = new UsernamePasswordAuthenticationToken(username, null, authorities);
                    authToken.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
                    SecurityContextHolder.getContext().setAuthentication(authToken);
                    try {
                        Integer userIdObj = jwtService.extractClaim(jwt, claims -> claims.get("userId", Integer.class));
                        if (userIdObj != null) {
                            request.setAttribute("X-User-Id", userIdObj.longValue());
                        }
                    } catch (Exception ignored) {
                    }
                    log.debug("Authenticated user \'{}\' with roles {}", username, authorities);
                }
            }
            filterChain.doFilter(request, response);
        } catch (Exception ex) {
            log.error("JWT authentication error: {}", ex.getMessage());
            response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Invalid or expired JWT token");
        }
    }

    @java.lang.SuppressWarnings("all")
    public JwtAuthFilter(final JwtService jwtService) {
        this.jwtService = jwtService;
    }
}
